"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { createLead } from "@/lib/api";
import { publicInstitute } from "@/lib/content";

export default function TrialClassPage() {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("sending"); const data = new FormData(event.currentTarget); try { await createLead({ instituteSlug: publicInstitute.slug, contactName: String(data.get("contactName")), phone: String(data.get("phone")), email: String(data.get("email") || "") || undefined, studentName: String(data.get("studentName") || "") || undefined, courseInterest: String(data.get("courseInterest") || "") || undefined, message: String(data.get("message") || "") || undefined }); event.currentTarget.reset(); setState("success"); } catch { setState("error"); } }
  return <main className="trial-page"><div className="trial-aside"><Link className="back-link" href={`/p/${publicInstitute.slug}`}>← {publicInstitute.name}</Link><span className="eyebrow">Free trial class</span><h1>Let&apos;s find<br /><em>the right fit.</em></h1><p>Tell us a little about your learner. Our team will get back to you to arrange a relaxed first class.</p><div className="trial-points"><span>01</span><div><strong>No pressure</strong><small>Meet the teacher and see how it feels.</small></div><span>02</span><div><strong>A clear next step</strong><small>We&apos;ll recommend a path that fits.</small></div></div></div><div className="trial-form-wrap"><form className="trial-form" onSubmit={submit}><div className="eyebrow">Your details</div><h2>Request a trial class</h2><div className="trial-fields"><label>Parent / contact name<input name="contactName" required placeholder="Your name" /></label><label>Phone number<input name="phone" required placeholder="081 234 5678" /></label><label>Student name<input name="studentName" placeholder="Learner name" /></label><label>Interested in<select name="courseInterest" defaultValue=""><option value="" disabled>Select a course</option><option>English Confidence</option><option>Math Foundations</option><option>Homework Studio</option><option>Not sure yet</option></select></label><label className="wide">Email address<input type="email" name="email" placeholder="you@example.com" /></label><label className="wide">Anything we should know?<textarea name="message" placeholder="Age, goals or preferred days" /></label></div>{state === "success" && <div className="form-message success">Thanks. Your request is with the academy team.</div>}{state === "error" && <div className="form-message error">We could not send this yet. Please check your connection and try again.</div>}<button className="public-cta submit" disabled={state === "sending"}>{state === "sending" ? "Sending..." : "Send my request →"}</button><small className="privacy-note">By sending this form, you agree that the academy may contact you about the trial class.</small></form></div></main>;
}
