-- Apply once on environments that already contain payments. Back up first.
ALTER TABLE payments
    ADD COLUMN receipt_pdf_url VARCHAR(1000) NULL;

-- Preserve links generated by the previous receipt path implementation.
UPDATE payments
SET receipt_pdf_url = CONCAT('https://storage.tiwhub.com/receipts/', invoice_no, '.pdf')
WHERE status = 'succeeded' AND receipt_pdf_url IS NULL;
