"use client";

import { FormEvent, useState } from "react";
import { Shell } from "@/components/Shell";
import { createLead } from "@/lib/api";

export default function LeadsPage() {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("sending"); const data = new FormData(event.currentTarget); try { await createLead({ instituteSlug: String(data.get("instituteSlug")), contactName: String(data.get("contactName")), phone: String(data.get("phone")), email: String(data.get("email") || "") || undefined, studentName: String(data.get("studentName") || "") || undefined, courseInterest: String(data.get("courseInterest") || "") || undefined, message: String(data.get("message") || "") || undefined }); event.currentTarget.reset(); setState("success"); } catch { setState("error"); } }
  return <Shell><header className="topbar"><div><span className="eyebrow">Growth / lead inbox</span><h1>Open the door.</h1><p className="subtitle">Send a real trial enquiry into the Academy API.</p></div><div className="profile"><div className="avatar">NS</div></div></header><div className="grid" style={{ gridTemplateColumns: "1fr .75fr", alignItems: "start" }}><form className="card" onSubmit={submit}><div className="card-heading"><h2>Test lead submission</h2><span className="pill">POST /api/public/leads</span></div><div className="form-grid"><div className="field"><label htmlFor="instituteSlug">Institute slug *</label><input id="instituteSlug" name="instituteSlug" placeholder="academy" required /></div><div className="field"><label htmlFor="contactName">Contact name *</label><input id="contactName" name="contactName" placeholder="Parent name" required /></div><div className="field"><label htmlFor="phone">Phone *</label><input id="phone" name="phone" placeholder="0812345678" required /></div><div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" placeholder="parent@example.com" /></div><div className="field"><label htmlFor="studentName">Student name</label><input id="studentName" name="studentName" placeholder="Student name" /></div><div className="field"><label htmlFor="courseInterest">Course interest</label><input id="courseInterest" name="courseInterest" placeholder="English, Math..." /></div><div className="field full"><label htmlFor="message">Message</label><textarea id="message" name="message" placeholder="Anything the academy should know?" /></div></div>{state === "success" && <p className="subtitle" style={{ color: "var(--green)", marginTop: 18 }}>Lead created successfully and returned by the API.</p>}{state === "error" && <p className="subtitle" style={{ color: "#b45d3c", marginTop: 18 }}>Could not submit. Check `NEXT_PUBLIC_API_URL` and the API response.</p>}<div className="actions"><button className="button primary" disabled={state === "sending"}>{state === "sending" ? "Sending..." : "Submit enquiry"}</button></div></form><div className="card"><div className="card-heading"><h2>Evidence checklist</h2></div><div className="activity"><div className="activity-item"><div className="activity-icon">01</div><div>Tenant is resolved from slug<small>Required by LeadService</small></div></div><div className="activity-item"><div className="activity-icon">02</div><div>Rate limit protects public intake<small>10 requests / IP / minute</small></div></div><div className="activity-item"><div className="activity-icon">03</div><div>Success and error states are visible<small>No silent form failure</small></div></div></div></div></div></Shell>;
}
