import type { Metadata } from "next";
import Link from "next/link";
import { publicInstitute } from "@/lib/content";

export function generateStaticParams() { return [{ slug: publicInstitute.slug }]; }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  await params;
  return { title: `${publicInstitute.name} | Learning with confidence`, description: publicInstitute.description };
}

export default function PublicInstitutePage() {
  return <main className="public-site"><nav className="public-nav"><strong><span className="public-mark">A</span> {publicInstitute.name}</strong><div><a href="#teachers">Teachers</a><a href="#courses">Courses</a><a href="#contact">Contact</a><Link className="public-cta small" href="/trial-class">Book a trial</Link></div></nav><section className="public-hero"><div><span className="eyebrow">Learning, made visible</span><h1>{publicInstitute.tagline}</h1><p>{publicInstitute.description}</p><div className="public-actions"><Link className="public-cta" href="/trial-class">Try a class free <span>→</span></Link><a className="public-link" href="#courses">Explore courses ↓</a></div></div><div className="hero-note"><span>01 / progress note</span><strong>Small steps<br />count here.</strong><p>Individual attention. Practical goals. A clear next step after every class.</p></div></section><section className="public-section" id="stories"><div className="section-intro"><span className="eyebrow">Student stories</span><h2>Progress worth<br /><em>sharing.</em></h2></div><div className="story-grid">{publicInstitute.stories.map((story) => <article className="story-card" style={{ background: story.color }} key={story.title}><span>Student story</span><h3>{story.title}</h3><p>{story.detail}</p><b>Read story →</b></article>)}</div></section><section className="public-section teachers-section" id="teachers"><div className="section-intro"><span className="eyebrow">The people here</span><h2>Teachers who<br /><em>notice.</em></h2></div><div className="teacher-grid">{publicInstitute.teachers.map((teacher) => <article className="teacher-card" key={teacher.name}><div className="teacher-avatar">{teacher.initials}</div><span>{teacher.role}</span><h3>{teacher.name}</h3><p>{teacher.bio}</p></article>)}</div></section><section className="public-section courses-section" id="courses"><div className="section-intro"><span className="eyebrow">Choose your next step</span><h2>Courses with<br /><em>room to grow.</em></h2></div><div className="course-grid">{publicInstitute.courses.map((course) => <article className="course-card" key={course.name}><div><span className="course-subject">{course.subject}</span><h3>{course.name}</h3><p>{course.detail}</p></div><div className="course-meta"><span>{course.sessions} sessions</span><strong>{course.price}</strong></div></article>)}</div></section><section className="public-contact" id="contact"><div><span className="eyebrow">Come say hello</span><h2>Ready when<br />you are.</h2></div><div><p>{publicInstitute.address}<br />{publicInstitute.phone}<br />LINE: {publicInstitute.lineId}</p><Link className="public-cta" href="/trial-class">Start with a free trial →</Link></div></section><footer className="public-footer"><span>{publicInstitute.name}</span><span>© 2026 · Built for visible progress</span></footer></main>;
}
